# Generated by Django 4.2.7 on 2026-08-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_rsvp_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
