# Generated by Django 6.0.3 on 2026-03-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_admissionapplication_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='is_read',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
