# Generated by Django 6.0.3 on 2026-03-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_remove_admissionapplication_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
