# Generated by Django 6.0.3 on 2026-03-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_contactinquiry_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
