# Generated by Django 6.0.3 on 2026-03-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_admissionapplication_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
