# Generated by Django 6.0.3 on 2026-04-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='Full YouTube URL or embed link')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
