# Generated by Django 6.0.3 on 2026-04-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='content_p1',
            field=models.TextField(blank=True, help_text='First paragraph of the blog.', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_p2',
            field=models.TextField(blank=True, help_text='Second paragraph of the blog.', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='quote',
            field=models.TextField(blank=True, help_text='A highlighted quote in the blog.', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Image shown on the blog list page.', null=True, upload_to='blogs/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, help_text='Large image shown inside the blog detail page.', null=True, upload_to='blogs/'),
        ),
    ]
