# Generated by Django 6.0.3 on 2026-04-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_remove_blog_content_blog_content_p1_blog_content_p2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload the PDF brochure', upload_to='brochures/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
