# Generated by Django 4.2.7 on 2026-04-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0014_brochure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('link', models.URLField(blank=True, help_text='Optional link for the notification', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
